### ISSUE TITLE
I downloaded and installed it from the official source of "pypi.org", and found that "including dependencies" is not supported

### ISSUE THREAD

**Issue by liquanchen9** [scrapy/scrapyd-client#107]
the official source :  https://pypi.org/project/scrapyd-client/1.2.0/
What's wrong？

**Comment by liquanchen9** [comment]
The versions are the same 1.2.0
I'm a little confused

**Comment by jpmckinney** [comment]
The version with `--include-deps` was in development and not released. 1.2.1 is now released and includes it. Note that it is now `--include-dependencies`.
