### ISSUE TITLE
ModuleNotFoundError: No module named 'gazeta.settings' - after eggfining an spider

### ISSUE THREAD

**Issue by pjabol** [scrapy/scrapyd-client#112]
Hi!
I'm having a problem with running spider in scrapyd. After egging a spider with a command 
`scrapyd-deploy --build-egg gazeta.egg`
and trying to upload it through scrapydweb (or directly through scrapyd-deploy to scrapyd) I got the following error

**error**
```
(venv) PS J:\FN\gazeta> scrapyd-deploy
Packing version 1656977332
Deploying to project "gazeta" in http://localhost:6800/addversion.json
Server response (200):
Traceback (most recent call last):
  File "j:\fn\venv\lib\site-packages\scrapyd\webservice.py", line 21, in render
    return JsonResource.render(self, txrequest).encode('utf-8')
  File "j:\fn\venv\lib\site-packages\scrapyd\utils.py", line 21, in render
    r = resource.Resource.render(self, txrequest)
  File "j:\fn\venv\lib\site-packages\twisted\web\resource.py", line 262, in render
    return m(request)
  File "j:\fn\venv\lib\site-packages\scrapyd\webservice.py", line 88, in render_POST
    spiders = get_spider_list(project, version=version)
  File "j:\fn\venv\lib\site-packages\scrapyd\utils.py", line 134, in get_spider_list
    raise RuntimeError(msg.encode('unicode_escape') if six.PY2 else msg)
RuntimeError: Traceback (most recent call last):
  File "c:\software\python3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\software\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "j:\fn\venv\lib\site-packages\scrapyd\runner.py", line 46, in <module>
    main()
  File "j:\fn\venv\lib\site-packages\scrapyd\runner.py", line 43, in main
    execute()
  File "j:\fn\venv\lib\site-packages\scrapy\cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "j:\fn\venv\lib\site-packages\scrapy\utils\project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "j:\fn\venv\lib\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
  File "c:\software\python3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gazeta.settings'
```
**Project Structure**
![scrapy_structure](https://user-images.githubusercontent.com/11735325/177226009-53ee55e7-8437-4fca-bb71-fda821961396.JPG)

**gazeta/gazeta/spiders/gazetacrawler.py**
```
import scrapy
import datetime
import json
import hashlib
from urllib.parse import urlparse
from ..items import sItem

class gazetacrawler(scrapy.Spider):
    name = "gazetacrawler"
(...)
```

**gazeta/gazeta/settings.py**
```
BOT_NAME = 'gazeta'

SPIDER_MODULES = ['gazeta.spiders']
NEWSPIDER_MODULE = 'gazeta.spiders'
(...)
```

**gazeta/scrapy.cfg**
```
[settings]
default = gazeta.settings

[deploy]
url=http://localhost:6800/
project=gazeta
username=***
password=***
```

gazeta/setup.py
```
from setuptools import setup, find_packages

setup(
    name         = 'gazeta',
    version      = '1.0',
    packages     = find_packages(),
    entry_points = {'scrapy': ['settings = gazeta.settings']},
)
```
**What I'm missing in this project?** spider is working correctly when running locally, but cannot work through scrapyd. 
Additionally scrapyd is running in this same virtual environment

[jpmckinney](https://github.com/jpmckinney) - do You have any thoughts?

**Comment by jpmckinney** [comment]
Try renaming the `name` in `setup.py` to something else. Right now you have a `gazeta` package that contains a `gazeta` module, and this is very likely confusing to Python's import logic.

**Comment by Lyian** [comment]
My setup looks pretty much equivalent to @pjabol. I tried to rename or remove the the name key from setup.py but I still get the same error message. Any ideas? Thanks!

**Comment by pjabol** [comment]
@Lyian - in my case, changing `name` in `setup.py `resolved my problem - remeber to rename also entrypoints in `setup.py`.

**Comment by Lyian** [comment]
It looks like the error message was kind of confusing me. I tried in my terminal again and scrapyd-deploy gave me another error message, that one of my submodules within the scrapy project was not a module. 

Adding an init.py resolved the error and scrapyd-deploy was able to deploy my spiders.
Thanks for you help @pjabol  and I wish a happy new year ;).

**Comment by iAxiang** [comment]
scrapyd-client: 1.2.3
I get same problem, but i changing `name` in `setup.py` and remove the name key also same, has any ideas?

**Comment by jpmckinney** [comment]
You would have to provide more information like in the above messages, but this error is not caused by Scrapyd but by your own directory structure and/or setup.py file.

**Comment by iAxiang** [comment]
`├── ./__init__.py
├── ./demorun.sh
├── ./proj_hktv_video
│   ├── ./proj_hktv_video/__init__.py
│   ├── ./proj_hktv_video/items.py
│   ├── ./proj_hktv_video/middlewares.py
│   ├── ./proj_hktv_video/pipelines.py
│   ├── ./proj_hktv_video/settings.py
│   └── ./proj_hktv_video/spiders
│       ├── ./proj_hktv_video/spiders/__init__.py
│       ├── ./proj_hktv_video/spiders/hktv_single_spider.py
│       └── ./proj_hktv_video/spiders/hktv_spider.py
├── ./scrapy.cfg
├── ./setup.py
├── ./start_hktv_single_spider.py
├── ./start_hktv_spider.py
└── ./utils
    ├── ./utils/CommonUtils.py
    └── ./utils/__init__.py`

proj_hktv_video/proj_hktv_video/settings.py
`# -*- coding: utf-8 -*-
BOT_NAME = 'proj_hktv_video'
SPIDER_MODULES = ['proj_hktv_video.spiders']
NEWSPIDER_MODULE = 'proj_hktv_video.spiders'
......
`

proj_hktv_video/scrapy.cfg
`
[settings]
default = proj_hktv_video.settings

[deploy:proj_hktv_video]
url = http://127.0.0.1:6800/
project = proj_hktv_video
`

proj_hktv_video/setup.py
`
from setuptools import setup, find_packages

setup(
    name         = 'project',
    version      = '1.0',
    packages     = find_packages(),
    entry_points = {'scrapy': ['settings = proj_hktv_video.settings']},
)
`

May I ask if there is a problem with my directory structure or setup file? 
The scrapy project is running normal on shell
Thanks for your help

**Comment by jpmckinney** [comment]
What if you omit `name` entirely?

**Comment by iAxiang** [comment]
```
from setuptools import setup, find_packages

setup(
    version      = '1.0',
    packages     = find_packages(),
    entry_points = {'scrapy': ['settings = proj_test_video.settings']},
)
```
If I omit the name field, the same error still occurs
```
ModuleNotFoundError: No module named 'proj_test_video.settings'
```

**Comment by jpmckinney** [comment]
Hmm, and what specific command are you running to deploy your project to Scrapyd, and to schedule a crawl?

**Comment by iAxiang** [comment]
```
./proj_test_video> scrapyd-deploy proj_test_video
```
I use this command deploy to scrpyad, that it show "ModuleNotFoundError: No module named 'proj_test_video.settings'"

**Comment by jpmckinney** [comment]
Ah, I think because you have an `__init__.py` in both `proj_test_video` and `proj_test_video/proj_test_video`, Python looks for `settings` in the first `proj_test_video`.

Deleting the first `proj_test_video/__init__.py` (if it's not needed) might solve the issue.

Please avoid reusing module names across directories. It will save you a lot of trouble in Python.
