### ISSUE TITLE
How to get the path of package_data, not file bytes?

### ISSUE THREAD

**Issue by Resalee** [scrapy/scrapyd-client#113]
I've read about this:https://github.com/scrapy/scrapyd-client#egg-caveats, but `pkgutil.get_data()` gives me the file's bytes. I also tried `pkg_resources.get_resource_filename()` but it return "no such file or directory" when deploy the project.  I want to get the path of the file and read it through a package function which will open the file and read it by itself. 

Structure:
```
project
  --tools
      --custom.txt
  --spiders
  --setup.py
```

setup.py
```python
from setuptools import setup, find_packages

setup(
    name         = 'project',
    version      = '1.0',
    packages     = find_packages(),
    package_data={'tools': ['*.txt']},
    entry_points = {'scrapy': ['settings = project.settings']},
)
```

spider:
```python
from LAC import LAC
import pkg_resources

custom = pkg_resources.resource_filename('tools', 'custom.txt')

lac = LAC(mode='lac')
lac.load_customization(custom, sep=None)
```
the source code of the function:
from https://github.com/baidu/lac/blob/master/python/LAC/custom.py
![custom](https://user-images.githubusercontent.com/14049164/188842362-433dac4b-66df-4c4c-b6fc-3f29866ce266.png)

deploy error:
![deploy](https://user-images.githubusercontent.com/14049164/188850599-0d174001-fcbe-4b33-b85a-bc57f3109d7d.png)

**Comment by jpmckinney** [comment]
When a file is within an egg, it doesn't have a path on the filesystem. So, you can't get its filename.

As a workaround, you can create a [tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html), and pass its name to your function.
