### ISSUE TITLE
Why isn't the version extracted from setup.py?

### ISSUE THREAD

**Issue by lufte** [scrapy/scrapyd-client#12]
scrapyd-client uses a setup.py file to eggify the project. Why isn't the version number defined in that file automatically used when deploying the project to scrapyd? Or at least provide a way to tell scrapyd-client to use that value.

**Comment by pablohoffman** [comment]
I don't think there is a strong reason, we probably never added this.

**Comment by Digenis** [comment]
Because this would mean that `setup.py` would need to be overwritten on every deployment.
Another way would be to make `setup.py` get the version on build time.
@lufte, do you have a usecase?

**Comment by jpmckinney** [comment]
Closing as no response to question.
