### ISSUE TITLE
Add a client for python

### ISSUE THREAD

**Issue by mxdev88** [scrapy/scrapyd-client#120]
I would like to access a `scrapyd` instance from within python code directly.

I would propose something like below:

```py
from scrapyd_client import ScrapydClient

client = ScrapydClient(url='http://localhost:6800')

client.projects()
``` 

The API would expose the commands already implemented within `scrapyd-client`. `scrapyd-client` already has most of the code necessary to accomplish this with little effort. most of it would be wrapper around lib.

Does it make sense? If so, happy to contribute a PR.

**Comment by jpmckinney** [comment]
Makes sense!
