### ISSUE TITLE
schedule only accepts one setting argument

### ISSUE THREAD

**Issue by mxdev88** [scrapy/scrapyd-client#124]
For example:

```sh
scrapyd-client schedule -p project1 spider1 --arg 'setting=DOWNLOADER_MIDDLEWARES={"my.middleware.MyDownloader": 610}' --arg 'setting=OTHER_SETTING=1'
```

Only the last setting value is past to scrapyd. 

This is because `commands.py` uses a dict rather than a list of tuple.

https://github.com/scrapy/scrapyd-client/blob/eb221c170f4d7ad75b50d81090a648516a53c6e5/scrapyd_client/commands.py#L28 

potentially to be changed into :

```py
job_args = [(x[0], x[1]) for x in (y.split("=", 1) for y in args.arg)]
```

And in `lib.py`, the use of dict.update().

https://github.com/scrapy/scrapyd-client/blob/eb221c170f4d7ad75b50d81090a648516a53c6e5/scrapyd_client/lib.py#L95

potentially to be changed into :

```py
data += [("project", project), ("spider", spider)]
```

Thoughts?

**Comment by mxdev88** [comment]
If we need to keep lib accept `dict` for retro compatibility, we could do that.

```py
def schedule(url, project, spider, args:Union[Dict,List[Tuple]]={}, username=None, password=None):
```

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
I think it’s fine to no longer accept dict - thank you!

**Comment by mxdev88** [comment]
> I think it’s fine to no longer accept dict - thank you!

That makes sense!
