### ISSUE TITLE
scrapyd-deploy on Windows 

### ISSUE THREAD

**Issue by PoulTur** [scrapy/scrapyd-client#13]
It seems there is some issue with scrapyd-client on Windows. The scrapyd-deploy file is via pip install saved into the c:\Python27\Scripts directory, but it is not available then in the command line via scrapyd-deploy. My path in Windows is properly set to include it.

I experimented with various options, and funny thing scrapyd-deploy command works when I copied the scrapyd-deploy file directly to my project folder. Then via command "python scrapyd-deploy -l" ran from cd to project directory 'm able to get the command working. However it does not look like it is the right solution... For various spiders  I would need to copy this for all projects, wouldn't this cause some conflicts?

I would be happy to get a perspective if this is worth to keep on trying with scrapyd for Windows, or perhaps it is not really meant for Windows?

**Comment by pablohoffman** [comment]
From a project goal POV, `scrapyd-deploy` should work on windows. Scrapyd server no.

**Comment by PoulTur** [comment]
Ok, thank you. This is good to know about Scrapyd server - I actually managed to run scrapyd (likely meaning server) on Windows, I just could not do scrapyd-deploy the way I would expect. I found that scrapyd-deploy works on Windows, but I did not find a workaround without copying the copy of scrapyd-deploy file straight to each project locations individually.

**Comment by kimg1234** [comment]
scrapyd-deploy run in windows
step1:
create a file ,name as "scrapyd-deploy.bat" 
step2:
Enter the following content
"""
@echo off

"D:\python27\python.exe" "D:\python27\Scripts\scrapyd-deploy" %1 %2 %3 %4 %5 %6 %7 %8 %9
"""

my python install in D:\python27\ ,
Environment Variables in D:\python27\Scripts\

**Comment by kimg1234** [comment]
![1](https://cloud.githubusercontent.com/assets/15347911/16033059/766253e6-323c-11e6-9c62-d1a772406e14.jpg)
![2](https://cloud.githubusercontent.com/assets/15347911/16033060/769219b4-323c-11e6-98ea-502209e33d4b.jpg)

**Comment by datawizard1337** [comment]
Thanks, Jin!
That helped a lot!

**Comment by Mee1ad** [comment]
you should say "python scrapyd-deploy" instead "scrapyd-deploy"

**Comment by my8100** [comment]
Alternatively, you can simply use the **Auto Packaging** feature of [ScrapydWeb](https://github.com/my8100/scrapydweb) to deploy your projects via web UI.

**Comment by jpmckinney** [comment]
The tests run on Windows #85. I believe this issue was resolved.
