### ISSUE TITLE
'scrapyd-deploy local -p project' hangs

### ISSUE THREAD

**Issue by jchan-scc** [scrapy/scrapyd-client#14]
Hi everyone

Does anyone know why when i run the aforementioned command, it just hangs at
Packing version 1448991014

if I do this scrapyd-deploy -l
I can see
local                http://localhost:6800/

I have 100s of spiders in the spiders directory, is that why it may hang?

Thanks
Joyce

**Comment by jpmckinney** [comment]
That command only reads the [Scrapy configuration files](https://docs.scrapy.org/en/latest/topics/commands.html#configuration-settings), so it should return almost immediately. I recommend trying the latest version of scrapyd-client.
