### ISSUE TITLE
different machine deploy spider by scrapyd-deploy

### ISSUE THREAD

**Issue by xyniceboy** [scrapy/scrapyd-client#17]
## useage

``` python
import commands
commands.getstatusoutput('scrapyd-deploy vmaxcrawler -p crawlers_husoe')
```
## result

```
Deploying to project "crawlers_husoe" in http://192.168.125.1:6800/addversion.json
Traceback (most recent call last):
  File "/usr/local/bin/scrapyd-deploy", line 273, in <module>
    main()
  File "/usr/local/bin/scrapyd-deploy", line 96, in main
    if not _upload_egg(target, egg, project, version):
  File "/usr/local/bin/scrapyd-deploy", line 195, in _upload_egg
    return _http_post(req)
  File "/usr/local/bin/scrapyd-deploy", line 211, in _http_post
    f = urllib2.urlopen(request)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by Digenis** [comment]
I can't work with this; I need more info.
Try 'curl http://192.168.125.1:6800/addversion.json`.
What is your scrapyd config in the `vmaxcrawler` machine?

**Comment by xyniceboy** [comment]
i used it in django, and set the scrapy.cfg as follow:
"""
[deploy:vmaxcrawler ]
url = http://192.168.125.1:6800
username = root
password = root
"""

**Comment by Digenis** [comment]
Does the curl command I gave you work at all?

**Comment by xyniceboy** [comment]
A pc is a linux pc, B pc is also a linux pc（192.168.125.1）. need deploy spider-egg to B pc as follow, python shell is ok, linux shell is also ok, but by django architecture use it, what is so incredible like the ## result
"
import commands
commands.getstatusoutput('scrapyd-deploy vmaxcrawler -p crawlers_husoe')
"

**Comment by xyniceboy** [comment]
the curl command need to pack spider egg first, so i use "scrapyd-deploy project -p project" directly

**Comment by Digenis** [comment]
Just run on computer "A" the curl command I gave you
and paste here the result.

**Comment by xyniceboy** [comment]
[root@bwa vmaxcrawler]# curl http://192.168.125.1:6800/addversion.json
{"status": "error", "message": "['HEAD', 'object', 'POST']", "node_name": "ER1245637"}

**Comment by Digenis** [comment]
But isn't vmaxcrawler computer "A"?

**Comment by xyniceboy** [comment]
no, it is. why did you say that?

**Comment by Digenis** [comment]
This is confusing.
I'm trying to make sure it's not a network/firewall issue.
I guess it's not.

Maybe scrapyd-deploy fails but curl works.
Replace your python snippet with this:
```python
import commands
commands.getstatusoutput('curl http://192.168.125.1:6800/addversion.json')
```
Does this give you some curl network error
or `{"status": "error", "message": "['HEAD', 'object', 'POST...`?

Also, what is the output of `which -a scrapyd-deploy`?

**Comment by xyniceboy** [comment]
1. the "addversion.json" API must have the parameters like "project, version, egg"
as say: http://scrapyd.readthedocs.org/en/latest/api.html#addversion-json

''' 
$ curl http://localhost:6800/addversion.json -F project=myproject -F version=r23 -F egg=@myproject.egg
'''

and, I execute the follow commands in python shell is still ok, but the django is still incredible.

'''
commands.getstatusoutput('python setup.py bdist_egg')
commands.getstatusoutput('curl http://192.168.125.1:6800/addversion.json  -F project=crawlers_husoe -F version=r01 -F egg=@vmaxcrawler-1.0.0-py2.7.egg')
'''

2. [root@zdh1en dist]# which -a scrapyd-deploy
/usr/local/bin/scrapyd-deploy

**Comment by xyniceboy** [comment]
1. the "addversion.json" API must have the parameters like "project, version, egg" as say: http://scrapyd.readthedocs.org/en/latest/api.html#addversion-json
''' 
$ curl http://localhost:6800/addversion.json -F project=myproject -F version=r23 -F egg=@myproject.egg
'''

and, I execute the follow commands in python shell is still ok, but the django is still incredible.
'''
commands.getstatusoutput('python setup.py bdist_egg')
commands.getstatusoutput('curl http://192.168.125.1:6800/addversion.json -F project=crawlers_husoe -F version=r01 -F egg=@vmaxcrawler-1.0.0-py2.7.egg')
'''

2. [root@bwa vmaxcrawler]# which -a scrapyd-deploy 
/usr/local/bin/scrapyd-deploy

**Comment by xyniceboy** [comment]
1. the "addversion.json" API must have the parameters like "project, version, egg" as say: http://scrapyd.readthedocs.org/en/latest/api.html#addversion-json ''' $ curl http://localhost:6800/addversion.json -F project=myproject -F version=r23 -F egg=@myproject.egg '''
and, I execute the follow commands in python shell is still ok, but the django is still incredible.
```
commands.getstatusoutput('python setup.py bdist_egg')
commands.getstatusoutput('curl http://192.168.125.1:6800/addversion.json -F project=crawlers_husoe -F version=r01 -F egg=@vmaxcrawler-1.0.0-py2.7.egg')
```
2.
```
[root@bwa vmaxcrawler]# which -a scrapyd-deploy 
/usr/local/bin/scrapyd-deploy
```

**Comment by xyniceboy** [comment]
1. the "addversion.json" API must have the parameters like "project, version, egg" 
as say: http://scrapyd.readthedocs.org/en/latest/api.html#addversion-json 
and, I execute the follow commands in python shell is still ok, but the django is still incredible.
`
commands.getstatusoutput('python setup.py bdist_egg')
commands.getstatusoutput('curl http://192.168.125.1:6800/addversion.json -F project=crawlers_husoe -F version=r01 -F egg=@vmaxcrawler-1.0.0-py2.7.egg')
`
2.
`
[root@bwa vmaxcrawler]# which -a scrapyd-deploy 
/usr/local/bin/scrapyd-deploy
`

**Comment by Digenis** [comment]
> the "addversion.json" API must have the parameters like "project, version, egg"

I know.
However in your bug report you say you get a network error.
(`socket.error: [Errno 104] Connection reset by peer`)
I don't understand however if the curl command in django worked or not.

Also, what does this output?
`python -c "print u'\n'.join([__import__(m).__file__ for m in 'socket', 'httplib', 'urllib2'])"`
(just in case you have any differences in django's import paths and the shell's)

**Comment by xyniceboy** [comment]
1. did the follow in django and python shell, the result is the same. 
print u'\n'.join([__import__(m).__file__ for m in 'socket', 'httplib', 'urllib2'])
/usr/local/lib/python2.7/socket.pyc
/usr/local/lib/python2.7/httplib.pyc
/usr/local/lib/python2.7/urllib2.pyc

2. 
the egg was packed in PC A. But add_project_version() shows: 

```
@#@URL: http://192.168.125.1:6800/addversion.json
[ERROR]: Connection error. URL: http://192.168.125.1:6800/addversion.json
```

[root@bwa dist]# ls
vmaxcrawler-1.0.0-py2.7.egg

The API like this:

```
def add_project_version(ip, project):
    url = 'http://%s:6800/addversion.json' % ip
    #post = '-F project=%s -F version=r01 -F egg=@./dist/vmaxcrawler-1.0.0-py2.7.egg' % project
	post = 'project=%s&version=r01&egg=@./dist/vmaxcrawler-1.0.0-py2.7.egg' % project
	return curl_module_post(url, post)

def curl_module_post(url, post, isprint=True):
    if isprint:
        print "@#@URL:", url
    c = pycurl.Curl()
    b = StringIO.StringIO()
    c.setopt(pycurl.URL, url)
    c.setopt(pycurl.WRITEFUNCTION, b.write)
    c.setopt(pycurl.POST, 1)
    c.setopt(pycurl.POSTFIELDS, post)

    try:
        c.perform()
    except:
        print "[ERROR]: Connection error. URL: %s" % url
    result = b.getvalue().replace('"prevstate": null', '"prevstate": "null"')
    c.close()
    b.close()
    return eval(result) if len(result) > 0 else {}
```

**Comment by Digenis** [comment]
There is obviously a communication problem here.

We are trying to debug something that breaks on the network level
but you are caught up trying to make it work in the application level.

When I'm asking you if some command works
instead of trying it and pasting here the result
you are explaining **why it should eventually not work**.
I need to ask the same question multiple times
until I get a straight answer.

I'm sorry but this is as far as I'm willing to go
especially for an issue that ends up becoming tech support.
Try asking in the scrapy community mailing list
https://groups.google.com/d/forum/scrapy-users
