### ISSUE TITLE
use scrapyd-deploy is error 

### ISSUE THREAD

**Issue by xiaowenjie21** [scrapy/scrapyd-client#18]
Server response (200):
{"status": "error", "message": "NameError: name 'TRUE' is not defined", "node_name": "ubuntu"}

What is the reason?

**Comment by Digenis** [comment]
Have you tried running scrapy shell inside the project?
Unfortunately we can't see the full traceback in your problem
because scrapyd keeps only its last line (something that should be fixed).

**Comment by xiaowenjie21** [comment]
thanks ,this is problem is my setting.py
