### ISSUE TITLE
scrapyd-deploy does not recognize -a option

### ISSUE THREAD

**Issue by zv86** [scrapy/scrapyd-client#19]
When trying to deploy to all targets using -a, scrapyd-deploy returns that it has no option -a, this option is also no listed in help

**Comment by Digenis** [comment]
it's not in a release yet
and I'm not sure it's going to make it into one, see #16

**Comment by zv86** [comment]
OK, but it would be a nice to have feature (and it is already in the documentation)

**Comment by Digenis** [comment]
Which documentation?

**Comment by Digenis** [comment]
@zv86, unfortunately, the right documentation for the release is the one in pypi.
In github, there was no branch or tag for the correct version of the documentation.
In any case, when you are looking on the master branch in github
you are looking at what you would have if you had installed
with  `pip install git+https://github.com/scrapy/scrapyd-client.git@master`.

I opened a different ticket regarding tags, release branches and documentation.
