### ISSUE TITLE
scrapyd-deploy & virtualenv

### ISSUE THREAD

**Issue by luigilabel** [scrapy/scrapyd-client#20]
When installed on a virtual environment, I needed to add  a scrapyd-deploy.bat file in scripts folder in order for it to be recognized by the active environment

One should expect that after pip installed the package you shouldn't need to make any fixtures to use the tool

Regards

**Comment by sjustfly** [comment]
but how to fix in mac?

**Comment by Digenis** [comment]
@luigilabel, @sjustfly, can you install from git?
This may be fixed already by #35

**Comment by redapple** [comment]
I've released [scrapyd-client 1.2.0a1](https://pypi.python.org/pypi/scrapyd-client/1.2.0a1) (it's an alpha release so to install you need `pip install --pre scrapyd-client`)
It uses console scripts for `scrapyd-client` and `scrapyd-deploy`.
