### ISSUE TITLE
Not compatible with python3

### ISSUE THREAD

**Issue by holymonk** [scrapy/scrapyd-client#21]
> File "/usr/local/bin/scrapyd-deploy", line 68
>     print "%-20s %s" % (name, target['url'])
>                    ^
> SyntaxError: invalid syntax

**Comment by manny-lee** [comment]
try this

https://github.com/manny-lee/scrapyd-client/blob/master/scrapyd-client/scrapyd-deploy

**Comment by Digenis** [comment]
Closing in favour of #29.
@holymonk, see my comment there if you want to test it.
If you do, we'll be glad to receive any feedback.
