### ISSUE TITLE
python3-wip deploying with 0 spiders

### ISSUE THREAD

**Issue by rolele** [scrapy/scrapyd-client#30]
Hey @redapple thanks for the py3 branch!
I have some trouble to make the python3-wip branch work.

the project I am trying to run is: https://github.com/rolele/kafka_pipeline
my code is py3 so I can not test this particular project with master branch.
I tried to deploy a py2 project with master and it works fine.

Here is my output for scrapyd-deploy (py3):
```
Deploying to project "kafka_pipeline" in http://192.168.77.21:6800/addversion.json
Server response (200):
{"node_name": "717b71513849", "project": "kafka_pipeline", "status": "ok", "version": "1477995177", "spiders": 0}
```
If I run the project using ``` scrapy crawl spider -o /houses.jl ``` it works fine.
How can I debug this ? there is very little feedback from what is happening.

**Comment by Digenis** [comment]
In this case the server's response won't help.
We need to see the generated eggs and `setup.py` file.
To keep the eggs, pass the `-d` option to scrapyd-deploy.

**Comment by rolele** [comment]
this is caused by the setting:
```
LOG_STDOUT = True
```
once I removed this setting everything is fine, my spider is included in the egg.
this is clearly a bug in scrapped-client.
here is the link to peoples having the same issue:
http://stackoverflow.com/questions/33646722/scrapyd-deploy-shows-0-spiders-by-scrapyd-client

**Comment by Digenis** [comment]
Then this is a bug in scrapy. See:
https://github.com/scrapy/scrapy/issues/1646
https://github.com/scrapy/scrapyd/issues/107

I'm closing this because there are already open tickets for the issue.
