### ISSUE TITLE
Releases/Branches/Tags

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd-client#31]
It looks like the repository had no tag nor a branch for the release.
I checked the package in pypi and found which commit matches it.
I tagged it with 1.0.1 and made a 1.0 branch.

I still have some trouble with readthedocs.
Maybe the only kind of plain "readme" file it supports is markdown.
Ours is rst.

**Comment by jpmckinney** [comment]
I've renamed 1.0.1 to v1.0.1 to match later tags.

On PyPI there's no files for 1.0, so I didn't tag that.
