### ISSUE TITLE
Scrapy sidpers drastically slows down after running for 5 mins

### ISSUE THREAD

**Issue by rakeshbhatt10** [scrapy/scrapyd-client#32]
I am using scrapy to scrape multiple sites and Scrapyd to run spiders.

I had written 7 spiders and each spider processes at least 50 start URLs. I have around 7000 URL's. 1000 URL's for each spider.

As i start placing jobs in ScrapyD with 50 start URL's per job. Initially all spiders responds fine but suddenly they start working really slow. While running those on localhost it gives high performance

While i run Scrapyd on localhost it gives me very high performance. As i publish jobs on Scrapyd server. Request response time drastically decreases

Response time for each start URL is really slow after some time on server

Settings looks like this:

    BOT_NAME = 'service_scraper'
    
    SPIDER_MODULES = ['service_scraper.spiders']
    NEWSPIDER_MODULE = 'service_scraper.spiders'
    
    
    USER_AGENT = 'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0'
    
    ROBOTSTXT_OBEY = False
    
    CONCURRENT_REQUESTS = 30
    
    DOWNLOAD_DELAY = 0
    
    CONCURRENT_REQUESTS_PER_DOMAIN = 1000
    
    
    ITEM_PIPELINES = {
       'service_scraper.pipelines.MongoInsert': 300,
    }
    
    MONGO_URL="mongodb://xxxxx:yyyy"
    
    
    EXTENSIONS = {'scrapy.contrib.feedexport.FeedExporter': None}
    
    
    HTTPCACHE_ENABLED = True

Hi had tried changing CONCURRENT_REQUESTS and CONCURRENT_REQUESTS_PER_DOMAIN nothing is working. We had hosted scrapyd in AWS EC2.

Thanks in advance

**Comment by redapple** [comment]
@rakeshbhatt10 , I've just unlocked your message on scrapy-users mailing list. It's a better place to troubleshoot such issues.
