### ISSUE TITLE
Plans to support all endpoints?

### ISSUE THREAD

**Issue by funkyfuture** [scrapy/scrapyd-client#36]
are there plans to support all of scrapyd's api endpoints with complementary cli commands?

**Comment by redapple** [comment]
I don't think there are plans for this, but it would be a nice addition.
Pull Requests welcome!

**Comment by funkyfuture** [comment]
ai'ght, i don't know when i will implement this, could be tomorrow or never.

my approach would be this:

- there would be several subcommands for a `scrapyd-client` command
- i need the following subcommands:
  - `schedule`
  - `projects` (listprojects)
  - `spiders` (listspiders)
- the `deploy` command would - in this first iteration - simply call the current `scrapyd-deploy` script
- mainly base it on the `requests` package
- no hacky code, so it can easily be extended with further subcommands and options
- also usable as simple library

any concerns and feedback are appreciated.

and one matter that propably raises such: i'm not keen on supporting Python 2 in user applications. but i'm able to.

**Comment by redapple** [comment]
[Scrapinghub's shub client](https://github.com/scrapinghub/shub) could be a good base for a revamped scrapyd client

**Comment by jpmckinney** [comment]
Closed by #37
