### ISSUE TITLE
typo in your tutorial

### ISSUE THREAD

**Issue by super1-chen** [scrapy/scrapyd-client#39]
Dear:
I found a typo in your readme,

**Comment by super1-chen** [comment]
```
scrapyd-deploy -L exmaple
```
 should be changed to

```
   scrapyd-deploy -l exmaple 
```

**Comment by Digenis** [comment]
Hi, @super1-chen 

It's not a typo.
`-L`, in contrast to `-l`, takes a target name as an argument.
If you have suggestions on how the arguments should be parsed
feel free to discuss here or in a new issue.

**Comment by super1-chen** [comment]
thanks
