### ISSUE TITLE
add url as an option while using scrapyd-deploy

### ISSUE THREAD

**Issue by rolele** [scrapy/scrapyd-client#42]
Right now it suppose that the scrapyd-client is always sending the egg to the same url defined in the scrapy.cfg.
But if you have many scrapyd clients and you want to specify the url of your scrapyd server when you run the command: ```scrapyd-deploy```

Is there a way to specify the url of the scrapyd server using the command line level?

**Comment by redapple** [comment]
Hi @rolele ,
the current way to do that is to have [multiple targets](https://github.com/scrapy/scrapyd-client#targets) in your `scrapy.cfg`.
Would that work for you?

**Comment by rolele** [comment]
Hi @redapple ,
Ho so you mean I can have a section like this:
```
[example]
url=example.com
[test]
url=test.com
```
and deploy to scrapyd server example using:
```
scrapyd-deploy -L example
```
and deploy to scrapyd service test using:
```
scrapyd-deploy -L test
```
This is fine to me. It is exactly what I want to do.

**Comment by redapple** [comment]
Yep, though the syntax for [deploying to some target](https://github.com/scrapy/scrapyd-client#deploying-a-project) is:
```
scrapyd-deploy test
```
(i.e. without `-L`. `-L` is to list projects at a target)

**Comment by rolele** [comment]
yeah that is great! thanks
