### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by fujiiface** [scrapy/scrapyd-client#44]
Hello,

I just started using `scrapy` and wanted to deploy a spider to `scrapyd` but I can't seem to figure out how to install the `scrapyd-client`.  I'm new to Python so this will come off very noobish but how do I install this client?  I have `scrapyd` installed and working (console up, http://localhost:6800 accessible).  I installed the `scrapyd-client` using `pip` but I get the following error from the command line when I try to actually use it:

> 'scrapyd-deploy' is not recognized as an internal or external command, operable program or batch file.

I have a `scrapyd-deploy` FILE in my `C:\Users\Chris\AppData\Local\Programs\Python\Python36\Scripts` folder.  Examing that file shows it is just a .py file missing the extension.  I am doing all of this in Windows Server 2012 R2 using VirtualBox.

**Comment by fujiiface** [comment]
I was able to find some help with the scrapyd-client installation [here](http://stackoverflow.com/questions/37489247/scrapyd-deploy-l-opens-a-file-instead-of-running-command-in-windows).  Couple things to note:

1. I had to copy the scrapyd-client FILE from my python scripts folder (`C:\Users\Chris\AppData\Local\Programs\Python\Python36\Scripts`) to my project folder.  This is the same folder that has my `scrapy.cfg` file.

2. I had to add the .py file extension to the copied scrapyd-client file.

3. When calling the scrapyd-client from the Windows command line, I had to also include the `.py` extension.

Once the above steps were completed, I was able to run the following from the Windows command line:
`C:\path\to\crawler\project\scrapyd-deploy.py --deploy-all-targets`

**Comment by 92hackers** [comment]
https://stackoverflow.com/questions/45750739/scrapyd-client-command-not-found   answers the same question.

**Comment by onnkeat** [comment]
> https://stackoverflow.com/questions/45750739/scrapyd-client-command-not-found answers the same question.

The package on pypi is not the latest one. It still contains the problems mentioned by issue owner. Solution in website above suggests installing the package from Git directly.

Run the following command to install from Git: `pip install git+https://github.com/scrapy/scrapyd-client`
