### ISSUE TITLE
command not found: scrapyd-client

### ISSUE THREAD

**Issue by zhaozhong** [scrapy/scrapyd-client#47]
No exec file in '/lib/python2.7/site-packages/scrapyd-client', only 'scrapyd-deploy' file in it.

Command 'scrapyd-deploy' runs OK. Has 'scrapyd-client' been removed?

**Comment by redapple** [comment]
What version have you installed?

**Comment by zhaozhong** [comment]
1.1.0, installed in a virtualenv

**Comment by zhaozhong** [comment]
VERSION        __init__.py    __init__.pyc   scrapyd-deploy
only these 4 files in the folder

**Comment by zhaozhong** [comment]
Install by pip: pip install scrapyd-client

**Comment by redapple** [comment]
@zhaozhong , 
there's no official version with `scrapyd-client` command yet (which is in the current master branch README).
v1.1.0 only has `scrapyd-deploy`.

To get `scrapyd-client` command line client, you'll need to install from the master branch, something like this should do:
```
pip install --upgrade git+ssh://git@github.com/scrapy/scrapyd-client.git
```

**Comment by zhaozhong** [comment]
@redapple 
Ok, got it, thank you very much!
