### ISSUE TITLE
can fix the encoding problem:"environment can only contain strings"

### ISSUE THREAD

**Issue by evrn1874** [scrapy/scrapyd-client#49]
environment can only contain strings
many people meet
error message:
{"status": "error", "message": "environment can only contain strings", "node_name": "XSOOY-PC"}
when deploying project
I found this problem lies in the method get_spider_list() in utils.py of scrapyd
we must make sure that the value of the env passed into the Popen is str
But in fact env['SCRAPY_PROJECT'] and env['SCRAPY_EGG_VERSION'] these two parameters from the outside into the Unicode type, 
if in python3 is will fine, but in the python2 we must first convert  unicode to str , similar to the
Env['SCRAPY_PROJECT'] = str (project)
Env['SCRAPY_EGG_VERSION'] = str (version)
then is ok
could fix this problem in later version?   thanks~

**Comment by jpmckinney** [comment]
This sounds like a Python 2 issue. Python 2 is no longer supported.
