### ISSUE TITLE
How to run scrapyd-client

### ISSUE THREAD

**Issue by junejie** [scrapy/scrapyd-client#50]
Im wondering how to run the `scrapyd-client`. I installed `scrapyd` and `scrapyd-deploy` and i cant figure out how to run it base on the readme file.

**Comment by redapple** [comment]
@junejie , can you try isntalling scrapyd-client 1.2.0a1 with for example `pip install --upgrade --pre scrapyd-client`?

**Comment by junejie** [comment]
awesome.. now i have it. thanks
