### ISSUE TITLE
Python3 JSON datatype issue

### ISSUE THREAD

**Issue by rafspiny** [scrapy/scrapyd-client#53]
I am having a problem using the `scrapyd-deploy` utility.
When I run `scrapyd-deploy -L local` to list all of my projects, I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/scrapyd-deploy", line 292, in <module>
    main()
  File "/usr/local/bin/scrapyd-deploy", line 81, in main
    projects = json.loads(f.read())['projects']
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Apparently the solution would be to decode the input. So line 81 of scrapyd-deploy should become: 
```python
projects = json.loads(f.read().decode('utf-8'))['projects']
```
Am I the only one having this issue?

I am running Python 3.4 and this is the relevant output from pip:
```
$ pip list | grep -i scrapy

Scrapy (1.4.0)
scrapy-random-useragent (0.2)
scrapy-splash (0.7.2)
scrapyd (1.2.0)
scrapyd-client (1.1.0)
scrapyrt (0.10.0)
```

_edit: moved from https://github.com/scrapy/scrapyd/issues/264_

**Comment by borisalmonacid** [comment]
➜  webofsciencescrapy-master scrapyd-deploy -p webofscience 
Packing version 1517713364
Traceback (most recent call last):
  File "/usr/local/bin/scrapyd-deploy", line 292, in <module>
    main()
  File "/usr/local/bin/scrapyd-deploy", line 101, in main
    exitcode, tmpdir = _build_egg_and_deploy_target(target, version, opts)
  File "/usr/local/bin/scrapyd-deploy", line 121, in _build_egg_and_deploy_target
    egg, tmpdir = _build_egg()
  File "/usr/local/bin/scrapyd-deploy", line 259, in _build_egg
    retry_on_eintr(check_call, [sys.executable, 'setup.py', 'clean', '-a', 'bdist_egg', '-d', d], stdout=o, stderr=e)
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/python.py", line 353, in retry_on_eintr
    return function(*args, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', 'setup.py', 'clean', '-a', 'bdist_egg', '-d', '/var/folders/8c/_pzthwjd1bs6mv14kx7n50p40000gn/T/scrapydeploy-v5jE68']' returned non-zero exit status 1
➜  webofsciencescrapy-master pip list | grep -i scrapy
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
Scrapy (1.5.0)
scrapyd (1.2.0)
scrapyd-client (1.1.0)

**Comment by Digenis** [comment]
@rafspiny, the offending line is now at:
https://github.com/scrapy/scrapyd-client/blob/4d839039ccd7b84997ba3fd533df313701b5ab68/scrapyd_client/deploy.py#L83
Unicode is encoded within json using unicode escapes
so decoding of the json itself should be from ascii, not utf-8.

This doesn't happen in python3.6
because it implicitly decodes it
from one of the utf-somethings
https://bugs.python.org/issue17909

Decoding from utf-8 works because of utf-8's compatibility with ascii
but let's be correct and use ascii.

**Comment by Digenis** [comment]
I just noticed #28 and #29.
Maybe the correct encoding is utf-8 after all.

**Comment by jpmckinney** [comment]
[json.loads](https://docs.python.org/3.8/library/json.html#json.loads) can only read strings (not bytes) before Python 3.6. That said, versions of Python less than 3.6 are all end-of-life and are no longer supported. So, this issue can be closed. 

@borisalmonacid Your issue is #69.
