### ISSUE TITLE
sudo: unable to execute /usr/local/bin/scrapyd-deploy: No such file or directory

### ISSUE THREAD

**Issue by affemann2** [scrapy/scrapyd-client#55]
Hi . I am trying to get scrapyd to deploy but everytime I run the command

    sudo scrapyd-deploy local

I get the following error

    Unable to execute /usr/local/bin/scrapyd-deploy: No such file or directory

I did the following to try and trouble shoot:
reinstall python
pip install scrapy
pip install scrapyd
pip install scrapyd-client

I checked usr/local/bin and found that the following files exist:
scrapy
scrapyd
scrapyd-deploy

I'm not sure why the scrapy files exist in the folder but when I try to run scrapyd-deploy local it cannot find them. Thanks for your help

**Comment by my8100** [comment]
Alternatively, you can use [ScrapydWeb](https://github.com/my8100/scrapydweb) to deploy your project via web UI.

**Comment by affemann2** [comment]
I had upgraded to os mojave after which all of the errors started. 

I was able to resolve issue by starting over. I did the following:
brew uninstall python
pip uninstall scrapy
pip uninstall scrapyd
pip uninstall scrapyd-client
I deleted docker

I then reinstalled scrapyd-client after which the error resolved and I was able to deploy scrapyd.

**Comment by Digenis** [comment]
@affemann2, consider using tools such as virtualenv, pyenv and coda to avoid such problems in the future.
Don't use sudo for this.
