### ISSUE TITLE
How deploy to all host

### ISSUE THREAD

**Issue by pceuropa** [scrapy/scrapyd-client#63]
Hi,
I can't find in documentation, how deploy project on few hosts.

When I use
```bash
scrapyd-deploy http://ip -p name_project
```
I've received: `Unknown target: http://149.202.00.00`

I tried deploy by setup.cfg. But I cant find way how set many targets. 
My setup.cfg
```[settings]
default = project_name.settings

[deploy]
url = http://localhost:6800/
project = project_name
[deploy:example]
url = http://149.202.00.00:6800/
project = project_name

[something]
url = http://149.202.00.00:6800/,http://localhost:6800/
project = project_name
```
Command
```scrapyd-deploy -a -p project_name```
does deploy only on first URL adress or get message option 'url' in section 'deploy:example' already exists

**Comment by jpmckinney** [comment]
You need to do something like:

```ini
[deploy:main]
url = http://localhost:6800/
project = project_name

[deploy:example]
url = http://149.202.00.00:6800/
project = project_name
```

And then run:

```bash
scrapyd-deploy main
scrapyd-deploy example
```

You cannot deploy to both at once. If you want to do that regularly, I suggest writing a simple Bash script that runs the two commands.

**Comment by jpmckinney** [comment]
Oh, wait, hold on, you can use the `--deploy-all-targets` (`-a`) option!
