### ISSUE TITLE
BUG: Breaking changes on Scrapy>=2.5.0

### ISSUE THREAD

**Issue by psdon** [scrapy/scrapyd-client#72]
This library doesn't work with scrapy 2.5.0 and above.
If anyone also facing the same issue, downgrade it to `Scrapy==2.4.1`

**Comment by iamumairayub** [comment]
I forked repo and fixed that, you can run these commands in your system to fix that error

1) `pip uninstall scrapy-client`

2) `pip install git+https://github.com/iamumairayub/scrapyd-client.git --upgrade`

**Comment by ilias-ant** [comment]
Any updates on this from the maintainers?
