### ISSUE TITLE
No module named 'scrapy.utils.http'

### ISSUE THREAD

**Issue by v2sh1t** [scrapy/scrapyd-client#75]
typing 'scrapyd-deloy -h' then show me this message, maybe scrapy is too new? cannot found http module in site-packages/scrapy/utils really
![1](https://user-images.githubusercontent.com/46537200/119915331-dc7a4e00-bf94-11eb-9ab6-c7dc7c12e7dd.png)
![2](https://user-images.githubusercontent.com/46537200/119915336-dedca800-bf94-11eb-98ad-4bbe8f895476.png)
![3](https://user-images.githubusercontent.com/46537200/119915340-e13f0200-bf94-11eb-8374-ec3cda4274bd.png)

**Comment by iamumairayub** [comment]
Do this as suggested https://github.com/scrapy/scrapyd-client/issues/72#issuecomment-826646131

**Comment by v2sh1t** [comment]
> Do this as suggested [#72 (comment)](https://github.com/scrapy/scrapyd-client/issues/72#issuecomment-826646131)

thx, it great to useful

**Comment by vimagick** [comment]
ScrapyDeprecationWarning: Module `scrapy.utils.http` is deprecated, Please import from `w3lib.http` instead.

This PR solves the issue: https://github.com/scrapy/scrapyd-client/pull/76
